#![cfg(feature = "symbols")]
use std::{collections::HashMap, fs::File, io, io::prelude::*};

pub type Location = gb_sym_file::Location;
pub type Symbols = HashMap<Location, String>;

/// Load up a symbols file from a path and return a HashMap<Location, String>
pub fn load_sym_file(symfile_path: &str) -> io::Result<Symbols> {
    let handle = File::open(symfile_path)?;

    Ok(io::BufReader::new(handle)
        .lines()
        .filter_map(|l| l.ok())
        .map(|line| gb_sym_file::parse_line(&line))
        .flatten()
        .filter_map(|item| item.ok())
        .map(|(k, v)| (v, k))
        .collect())
}

#[cfg(test)]
mod test {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn test_load_sym_file() {
        let file_content = "; File generated by rgblink\n\
                        00:0038 RST38\n\
                        00:0150 EntryPoint\n\
                        00:0157 toto\n\
                        01:4000 Plop\n\
                    ";

        let mut file = NamedTempFile::new().unwrap();
        write!(file, "{}", file_content).unwrap();

        let file_path = file.path().to_str().unwrap().to_string();

        let symbols = load_sym_file(&file_path).unwrap();

        let expected = Symbols::from([
            (Location::Banked(0, 0x38), "RST38".into()),
            (Location::Banked(0, 0x150), "EntryPoint".into()),
            (Location::Banked(0, 0x157), "toto".into()),
            (Location::Banked(1, 0x4000), "Plop".into()),
        ]);

        assert_eq!(symbols, expected);
    }
}
