use super::*;

use tempfile::NamedTempFile;
use std::{io::prelude::*};
use symbols::*;

#[test]
fn test_prefs_with_symbols() {
    let file_content = "; File generated by rgblink\n\
                        00:0038 RST38\n\
                        00:0150 EntryPoint\n\
                        00:0157 toto\n\
                        01:4000 Plop\n\
                    ";

    let mut file = NamedTempFile::new().unwrap();
    write!(file, "{}", file_content).unwrap();

    let file_path = file.path().to_str().unwrap().to_string();

    let prefs = Preferences::new_with_symbols_file(&file_path).unwrap();

    let expected = Symbols::from([
        (Location::Banked(0, 0x38), "RST38".into()),
        (Location::Banked(0, 0x150), "EntryPoint".into()),
        (Location::Banked(0, 0x157), "toto".into()),
        (Location::Banked(1, 0x4000), "Plop".into()),
    ]);

    assert_eq!(prefs.symbols, expected);
}

#[test]
fn test_render_symbols() {
    let file_content = "; File generated by rgblink\n\
                        00:0000 Start\n\
                        00:0005 Next\n\
                        00:0038 RST38\n\
                        00:0150 EntryPoint\n\
                        00:0157 toto\n\
                        01:4000 Plop\n\
                    ";
    let mut file = NamedTempFile::new().unwrap();
    write!(file, "{}", file_content).unwrap();
    let file_path = file.path().to_str().unwrap().to_string();
    let prefs = Preferences::new_with_symbols_file(&file_path).unwrap();

    let bus = SimpleBus::new(vec![0xC3, 0x50, 0x01]);
    let result = disassemble(&bus, 0x00, &prefs);

    assert_eq!(result, Ok((3, "jp EntryPoint <$0150>".to_string())));

    let bus = SimpleBus::new(vec![0xC2, 0x50, 0x01]);
    let result = disassemble(&bus, 0x00, &prefs);

    assert_eq!(result, Ok((3, "jp nz, EntryPoint <$0150>".to_string())));

    let bus = SimpleBus::new(vec![0xC2, 0x00, 0x40]);
    let result = disassemble(&bus, 0x00, &prefs);

    assert_eq!(result, Ok((3, "jp nz, Plop <$4000>".to_string())));

    // Illegal but will work here
    let bus = SimpleBus::new(vec![0x18, 0xFE]);
    let result = disassemble(&bus, 0x00, &prefs);

    assert_eq!(result, Ok((2, "jr Start <-2>".to_string())));

    // Illegal but will work here
    let bus = SimpleBus::new(vec![0x18, 0x03]);
    let result = disassemble(&bus, 0x00, &prefs);

    assert_eq!(result, Ok((2, "jr Next <3>".to_string())));
}
